import 'package:ai_chat_app/presentation/commonproblems/models.dart';

const List<DeviceFault> jand4002Faults = [
  DeviceFault(
    code: 'AL.051',
    name: 'EEPROM参数异常',
    mechanism: '伺服单元EEPROM数据异常',
    troubleshoot: '正确接线，重新上电。若始终出现，则更换驱动器。',
  ),
  DeviceFault(
    code: 'AL.052',
    name: '可编程逻辑配置故障',
    mechanism: '主控MCU上电初始化异常；内部通讯异常。',
    troubleshoot: '若始终出现，则更换驱动器。',
  ),
  DeviceFault(
    code: 'AL.053',
    name: '初始化失败',
    mechanism: '主控MCU上电初始化失败。',
    troubleshoot: '检查接线；重新上电；若始终出现，则更换驱动器。',
  ),
  DeviceFault(
    code: 'AL.054',
    name: '系统异常',
    mechanism: '主控MCU运行异常。',
    troubleshoot: '检查接线；重新上电；若始终出现，则更换驱动器。',
  ),
  DeviceFault(
    code: 'AL.060',
    name: '产品型号选择故障',
    mechanism: '产品参数设定与实际硬件不匹配；驱动器功率与电机功率不匹配。',
    troubleshoot: '正确设定产品参数；使用相匹配的驱动器和电机；若始终出现，则联系生产厂家。',
  ),
  DeviceFault(
    code: 'AL.061',
    name: '产品匹配故障',
    mechanism: '伺服单元与伺服电机型号不配。',
    troubleshoot: '检测伺服单元是否支持该款电机；更换与电机匹配的伺服单元。',
  ),
  DeviceFault(
    code: 'AL.062',
    name: '参数存储故障',
    mechanism: '参数存储异常。',
    troubleshoot: '重新上电；若始终出现，则更换驱动器。',
  ),
  DeviceFault(
    code: 'AL.063',
    name: '过电流检出',
    mechanism: 'U,V,W相间短路；驱动器损坏。',
    troubleshoot: '正确接线；若无报警检查动力线及电机是否存在短路；若断开U,V,W连接启动驱动器仍报警则更换驱动器。',
  ),
  DeviceFault(
    code: 'AL.064',
    name: '伺服上电自检发现输出对地短路故障',
    mechanism: '输出对地短路。',
    troubleshoot: '检查接线；正确接线；若始终出现，则更换驱动器。',
  ),
  DeviceFault(
    code: 'AL.065',
    name: '伺服单元内置风扇停止',
    mechanism: '内置风扇故障。',
    troubleshoot: '更换风扇或驱动器。',
  ),
  DeviceFault(
    code: 'AL.066',
    name: '伺服单元控制电源电压低',
    mechanism: '控制电源L,N电源电压过低。',
    troubleshoot: '检查接线是否正确；测量L,N电压是否低于140VAC；正确接线；若始终出现，则更换驱动器。',
  ),
  DeviceFault(
    code: 'AL.070',
    name: 'AD采样故障1',
    mechanism: 'AD采样数据异常。',
    troubleshoot: '检查接线；正确接线；若始终出现，则更换驱动器。',
  ),
  DeviceFault(
    code: 'AL.071',
    name: '电流采样故障',
    mechanism: '电流传感器件采样数据异常。',
    troubleshoot: '接线是否正确；正确接线；若始终出现，则更换驱动器。',
  ),
  DeviceFault(
    code: 'AL.100',
    name: '参数组合异常',
    mechanism: '参数设定错误。',
    troubleshoot: '检查已设定（P03-07）参数；正确设定参数；若始终出现请进行参数初始化。',
  ),
  DeviceFault(
    code: 'AL.101',
    name: 'AI设定故障',
    mechanism: 'AI设定异常。',
    troubleshoot: '检查AI设定参数；正确设定参数。',
  ),
  DeviceFault(
    code: 'AL.102',
    name: 'DI分配故障',
    mechanism: '至少有2个输入端口的功能选择一致。',
    troubleshoot: '检查输入端口功能选择参数（P06-01、P06-03、P06-05...）；正确设定参数；驱动器重新上电。',
  ),
  DeviceFault(
    code: 'AL.105',
    name: '电子齿轮设定错误',
    mechanism: '电子齿轮比设定错误；龙门输出脉冲设定过小。',
    troubleshoot: '正确设定电子齿轮比（P03-10,P03-11）；正确设定龙门功能电机旋转一圈反馈脉冲数（P03-52必须大于128）。',
  ),
  DeviceFault(
    code: 'AL.106',
    name: '分频脉冲输出设定异常',
    mechanism: '分频脉冲输出参数设定超出范围。',
    troubleshoot: '检查分频脉冲输出设置参数（P03-22,P03-23,P03-25）；正确设定分频脉冲输出参数；驱动器重新上电。',
  ),
  DeviceFault(
    code: 'AL.110',
    name: '参数设定后需重新上电',
    mechanism: '伺服参数设定后需重新上电才可生效。',
    troubleshoot: '驱动器重新上电。',
  ),
  DeviceFault(
    code: 'AL.120',
    name: '伺服ON指令无效警报',
    mechanism: '伺服ON时功率电源输入端口R,S,T未供电。',
    troubleshoot: '检查接线及输入电压；检查接线；驱动器重新上电。',
  ),
  DeviceFault(
    code: 'AL.401',
    name: '欠电压',
    mechanism: '主回路输入电压低于额定电压值或无输入电压。',
    troubleshoot: '检查主回路输入R,S,T接线是否正确且电压值是多少伏（可通过d23.dcp监控母线电压）；确保接线正确使用正确的电压源或串接稳压器。',
  ),
  DeviceFault(
    code: 'AL.402',
    name: '过电压',
    mechanism: '主回路输入电压高于额定电压值；驱动器硬件故障；未接再生电阻或者再生电阻选型不对。',
    troubleshoot: '使用正确的电压源或串接稳压器；当确定输入电压正确后仍然过压报警请送回经销商或原厂检修；正确设定及外接再生电阻（确认P00-30设置为0或1）。',
  ),
  DeviceFault(
    code: 'AL.410',
    name: '过载（瞬时最大负载）',
    mechanism: '电机启动时机械处于卡死状态；驱动器硬件故障。',
    troubleshoot: '调整机械结构；确认机械部分正常仍报警请送回经销商或原厂检修。',
  ),
  DeviceFault(
    code: 'AL.411',
    name: '驱动器过载',
    mechanism: '驱动器超过额定负载。',
    troubleshoot: '换更大功率驱动器或降低负载。',
  ),
  DeviceFault(
    code: 'AL.412',
    name: '电机过载（连续最大负载）',
    mechanism: '超过驱动器额定负载连续使用；控制系统参数设定不当；电机接线错误。',
    troubleshoot: '换更大功率电机或降低负载（可通过监控模式中d13.oL.进行监控）；调整控制回路增益加减速设定时间减慢；正确接线。',
  ),
  DeviceFault(
    code: 'AL.420',
    name: '过速',
    mechanism: '输入速度命令过高；过速度判定参数设定不正确。',
    troubleshoot: '用信号检测计检测输入的信号是否正常；调整输入信号的频率；正确设定P04-05（超速报警值）。',
  ),
  DeviceFault(
    code: 'AL.421',
    name: '失控检出',
    mechanism: '电机动力线U,V,W接线错误；电机参数设置不正确。',
    troubleshoot: '正确接线；正确设定参数（检查P00-05及编码器参数设定）；转矩模式时请将P01-40设0关闭失控检出功能。',
  ),
  DeviceFault(
    code: 'AL.422',
    name: '飞车故障',
    mechanism: '电机速度失控。',
    troubleshoot: '检查接线；正确设定参数。',
  ),
  DeviceFault(
    code: 'AL.423',
    name: '速度不一致报警',
    mechanism: '电机动力线U,V,W接线错误；电机参数设置不正确。',
    troubleshoot: '正确接线；正确设定参数（检查P00-46/P04-12设定是否合理）。',
  ),
  DeviceFault(
    code: 'AL.425',
    name: 'AI采样电压过大',
    mechanism: 'AI采样电压超出范围。',
    troubleshoot: '检查输入电压；降低输入电压至规定范围。',
  ),
  DeviceFault(
    code: 'AL.430',
    name: '再生异常',
    mechanism: '再生电阻选用错误或未接外部再生电阻；参数设定错误。',
    troubleshoot: '检查再生电阻的连接状况；正确设定参数值（确认P00-30,P00-31,P00-32）。',
  ),
  DeviceFault(
    code: 'AL.431',
    name: '再生过载',
    mechanism: '再生电阻选用错误或未接外部再生电阻。',
    troubleshoot: '检查再生电阻的连接状况及再生电阻的阻值及功率是否合适；选择合适的再生电阻。',
  ),
  DeviceFault(
    code: 'AL.432',
    name: '再生短路开路',
    mechanism: '再生短路；再生开路。',
    troubleshoot: '检查B1/B3端口是否有短路；正确设定参数值（确认P00-30,P00-31,P00-32参数设定）。',
  ),
  DeviceFault(
    code: 'AL.435',
    name: '冲击电流限制电阻过载',
    mechanism: '冲击电流限制电阻过载。',
    troubleshoot: '检查接线；若始终出现则更换驱动器。',
  ),
  DeviceFault(
    code: 'AL.436',
    name: 'DB过载',
    mechanism: 'DB制动过载。',
    troubleshoot: '降低DB使用频率或更换更大功率驱动器。',
  ),
  DeviceFault(
    code: 'AL.440',
    name: '散热器过热',
    mechanism: '驱动器内部温度高于95℃。',
    troubleshoot: '检查驱动器的散热条件是否良好；改善驱动器的散热条件如果仍出现报警请将驱动器返厂检修。',
  ),
  DeviceFault(
    code: 'AL.441',
    name: '电机过热故障',
    mechanism: '电机温度过高。',
    troubleshoot: '检查电机负载；降低负载或更换更大功率电机。',
  ),
  DeviceFault(
    code: 'AL.500',
    name: '分频脉冲输出过速',
    mechanism: '分频脉冲输出速度过高。',
    troubleshoot: '降低电机转速；正确设定分频参数。',
  ),
  DeviceFault(
    code: 'AL.501',
    name: '位置偏差过大',
    mechanism: '位置偏差过大设置参数设定过小；增益值设定过小；内部转矩限幅值设定过小；外部负载过大。',
    troubleshoot: '加大P03-15（位置偏差过大设置）设定值；重新正确调整增益类参数；重新正确调整内部转矩限幅值；减轻负载或换大功率电机。',
  ),
  DeviceFault(
    code: 'AL.502',
    name: '全闭环编码器位置与电机位置偏差过大',
    mechanism: '全闭环编码器位置与电机位置偏差超出范围。',
    troubleshoot: '检查编码器安装；检查机械连接；重新调整参数。',
  ),
  DeviceFault(
    code: 'AL.505',
    name: 'P命令输入脉冲异常',
    mechanism: '脉冲命令频率高于额定输入频率。',
    troubleshoot: '用脉冲频率检测计检测输入频率是否高于额定输入频率；正确设定输入脉冲频率。',
  ),
  DeviceFault(
    code: 'AL.510',
    name: '龙门同动偏差过大',
    mechanism: '龙门同动位置偏差超出设定值。',
    troubleshoot: '检查机械连接；调整龙门同动位置比例增益（P03-55）。',
  ),
  DeviceFault(
    code: 'AL.550',
    name: '惯量辨识失败故障',
    mechanism: '惯量辨识过程中出现异常。',
    troubleshoot: '检查电机接线；确认负载是否过大；重新进行惯量辨识。',
  ),
  DeviceFault(
    code: 'AL.551',
    name: '回原点超时故障',
    mechanism: '执行回原点操作时间超时。',
    troubleshoot: '确认参数P03-68(搜索原点最长时间限定)是否合理；正确设定P03-68。',
  ),
  DeviceFault(
    code: 'AL.552',
    name: '角度辨识失败故障',
    mechanism: '角度辨识过程中出现异常。',
    troubleshoot: '检查编码器接线；重新进行角度辨识。',
  ),
  DeviceFault(
    code: 'AL.600',
    name: '编码器输出电源短路故障',
    mechanism: '编码器电源接线错误。',
    troubleshoot: '检查编码器电源+5V及GND是否接反；正确接线。',
  ),
  DeviceFault(
    code: 'AL.610',
    name: '增量式编码器脱线',
    mechanism: '增量式编码器HallU,HallV,HallW信号异常。',
    troubleshoot: '检查编码器接线；正确接线。',
  ),
  DeviceFault(
    code: 'AL.611',
    name: '增量式编码器Z信号丢失',
    mechanism: '增量式编码器Z信号丢失。',
    troubleshoot: '检查编码器接线；正确接线。',
  ),
  DeviceFault(
    code: 'AL.620',
    name: '总线式编码器脱线',
    mechanism: '总线式编码器通讯失败。',
    troubleshoot: '检查编码器接线；正确接线。',
  ),
  DeviceFault(
    code: 'AL.621',
    name: '读写电机编码器EEPROM参数异常',
    mechanism: '编码器读写异常。',
    troubleshoot: '检查编码器接线；正确接线。',
  ),
  DeviceFault(
    code: 'AL.622',
    name: '电机编码器EEPROM中数据校验错误',
    mechanism: '编码器EEPROM数据校验错误。',
    troubleshoot: '检查编码器接线；重新上电；若始终出现则更换编码器或驱动器。',
  ),
  DeviceFault(
    code: 'AL.640',
    name: '总线式编码器超速',
    mechanism: '总线式编码器速度值超过6000rpm。',
    troubleshoot: '检查编码器接线；确认编码器屏蔽线正确连接；降低速度；若连接正常请将驱动器返厂检修。',
  ),
  DeviceFault(
    code: 'AL.641',
    name: '总线式编码器过热',
    mechanism: '总线式编码器温度过高。',
    troubleshoot: '检查编码器工作环境温度；改善散热条件。',
  ),
  DeviceFault(
    code: 'AL.643',
    name: '总线式编码器电池低压故障',
    mechanism: '总线式编码器设置为多圈绝对值时外接电池电压低。',
    troubleshoot: '检查编码器外接电池电压确认高于3.0V；当电池电压低于3.0V更换电池；高于3V使用辅助功能AF_En0清除报警。',
  ),
  DeviceFault(
    code: 'AL.644',
    name: '总线式编码器多圈故障',
    mechanism: '总线式编码器多圈数据异常。',
    troubleshoot: '检查编码器接线；使用指令AF_En1清除多圈值。',
  ),
  DeviceFault(
    code: 'AL.645',
    name: '总线式编码器多圈溢出故障',
    mechanism: '总线式编码器旋转圈数超出范围。',
    troubleshoot: '可通过监控模式d21.ASH进行圈数监视多圈绝对式电机不能长时间一个方向转；使用指令AF_En1清除多圈值。',
  ),
  DeviceFault(
    code: 'AL.646',
    name: '总线式编码器通信异常1',
    mechanism: '总线式编码器通信异常。',
    troubleshoot: '检查编码器接线；确认屏蔽线连接正确。',
  ),
  DeviceFault(
    code: 'AL.647',
    name: '总线式编码器计数异常2',
    mechanism: '分体式编码器安装位置偏差大。',
    troubleshoot: '检查编码器；正确安装编码器。',
  ),
  DeviceFault(
    code: 'AL.648',
    name: '总线式编码器通信异常3',
    mechanism: '总线式编码器通信异常。',
    troubleshoot: '检查编码器接线；确认屏蔽线连接正确。',
  ),
  DeviceFault(
    code: 'AL.649',
    name: '总线式编码器通信异常4',
    mechanism: '总线式编码器通信异常。',
    troubleshoot: '检查编码器接线；确认屏蔽线连接正确。',
  ),
  DeviceFault(
    code: 'AL.650',
    name: '总线式编码器通信异常5',
    mechanism: '总线式编码器通信异常。',
    troubleshoot: '检查编码器接线；确认屏蔽线连接正确。',
  ),
  DeviceFault(
    code: 'AL.651',
    name: '总线式编码器通信异常6',
    mechanism: '总线式编码器通信异常。',
    troubleshoot: '检查编码器接线；确认屏蔽线连接正确。',
  ),
  DeviceFault(
    code: 'AL.652',
    name: '总线式编码器多圈多个故障',
    mechanism: '总线式编码器多圈多个数据异常。',
    troubleshoot: '检查编码器接线；使用辅助功能清除故障。',
  ),
  DeviceFault(
    code: 'AL.900',
    name: '位置偏差过大（警告）',
    mechanism: '位置偏差超出警告设定值。',
    troubleshoot: '检查位置指令和负载状况；适当加大位置偏差过大设定值。',
  ),
  DeviceFault(
    code: 'AL.901',
    name: '伺服ON时位置偏差过大（警告）',
    mechanism: '伺服ON时位置偏差超出范围。',
    troubleshoot: '检查位置指令和负载状况。',
  ),
  DeviceFault(
    code: 'AL.910',
    name: '电机过载（警告）',
    mechanism: '电机负载超过额定值。',
    troubleshoot: '降低负载或更换更大功率电机。',
  ),
  DeviceFault(
    code: 'AL.912',
    name: '驱动器过载（警告）',
    mechanism: '驱动器负载超过额定值。',
    troubleshoot: '降低负载或更换更大功率驱动器。',
  ),
  DeviceFault(
    code: 'AL.920',
    name: '再生过载（警告）',
    mechanism: '再生电阻过载。',
    troubleshoot: '检查再生电阻的连接状况及阻值功率是否合适。',
  ),
  DeviceFault(
    code: 'AL.921',
    name: 'DB过载（警告）',
    mechanism: 'DB制动过载。',
    troubleshoot: '降低DB使用频率。',
  ),
  DeviceFault(
    code: 'AL.925',
    name: '外接再生泄放电阻过小（警告）',
    mechanism: '外接再生泄放电阻阻值过小。',
    troubleshoot: '检查外接再生电阻阻值；更换合适阻值的再生电阻。',
  ),
  DeviceFault(
    code: 'AL.930',
    name: '绝对值编码器的电池警告',
    mechanism: '绝对值编码器电池电压低。',
    troubleshoot: '检查编码器外接电池电压确认高于3.0V；电池电压低于3.0V更换电池；高于时使用指令AF_En0清除报警。',
  ),
  DeviceFault(
    code: 'AL.941',
    name: '需重新接通电源的参数变更（警告）',
    mechanism: '修改参数后需重新上电后参数生效。',
    troubleshoot: '断电重启。',
  ),
  DeviceFault(
    code: 'AL.942',
    name: '写EEPROM频繁警告（警告）',
    mechanism: '写EEPROM操作过于频繁。',
    troubleshoot: '减少写EEPROM频率。',
  ),
  DeviceFault(
    code: 'AL.943',
    name: '串口通讯异常（警告）',
    mechanism: '串口通讯干扰大；串口波特率设置过高。',
    troubleshoot: '检查接线；检查串口通讯的波特率参数P00-21；线材上增加滤波器；降低串口通讯的波特率。',
  ),
  DeviceFault(
    code: 'AL.950',
    name: '超程警告提示（警告）',
    mechanism: '电机运行超出限位。',
    troubleshoot: '检查机械限位开关；向反方向运行。',
  ),
  DeviceFault(
    code: 'AL.951',
    name: '绝对值编码器角度初始化警告（警告）',
    mechanism: '绝对值编码器角度未初始化。',
    troubleshoot: '执行绝对值编码器角度初始化。',
  ),
  DeviceFault(
    code: 'AL.971',
    name: '欠电压警告（警告）',
    mechanism: '主回路输入电压低于额定值。',
    troubleshoot: '检查输入电压；使用正确的电压源或串接稳压器。',
  ),
  DeviceFault(
    code: 'AL.990',
    name: '散热器过热警告（警告）',
    mechanism: '驱动器内部温度偏高。',
    troubleshoot: '检查驱动器的散热条件是否良好；改善散热条件。',
  ),
  DeviceFault(
    code: 'AL.991',
    name: '输入缺相警告（警告）',
    mechanism: '主回路输入缺相。',
    troubleshoot: '检查主回路输入R,S,T接线；确保三相输入正常。',
  ),
];