import 'package:ai_chat_app/presentation/commonproblems/models.dart';

const List<DeviceParam> jand4002Params = [
  DeviceParam(
    code: 'P00-00',
    name: '电机编号',
    range: '0-65535',
    defaultVal: '2000',
    unit: '',
    change: '停机设定',
    effect: '重新上电',
    description: '出厂已设定好，无需设置。0: P0-01至P0-17起作用；2000: 绝对值编码器电机，此时P0-01至P0-05由驱动器自动辨识。',
  ),
  DeviceParam(
    code: 'P00-01',
    name: '电机额定转速',
    range: '1-6000',
    defaultVal: '---',
    unit: 'rpm',
    change: '停机设定',
    effect: '重新上电',
    description: '出厂已设定好，无需设置。',
  ),
  DeviceParam(
    code: 'P00-02',
    name: '电机额定转矩',
    range: '0.01-655.35',
    defaultVal: '---',
    unit: 'N.M',
    change: '停机设定',
    effect: '重新上电',
    description: '根据所配电机设置，出厂已设好。',
  ),
  DeviceParam(
    code: 'P00-03',
    name: '电机额定电流',
    range: '0.01-655.35',
    defaultVal: '---',
    unit: 'A',
    change: '停机设定',
    effect: '重新上电',
    description: '根据所配电机设置，出厂已设好。',
  ),
  DeviceParam(
    code: 'P00-04',
    name: '电机转动惯量',
    range: '0.01-655.35',
    defaultVal: '---',
    unit: 'kg.cm²',
    change: '停机设定',
    effect: '重新上电',
    description: '根据所配电机设置，出厂已设好。',
  ),
  DeviceParam(
    code: 'P00-05',
    name: '电机极对数',
    range: '1-31',
    defaultVal: '---',
    unit: '对极',
    change: '停机设定',
    effect: '重新上电',
    description: '根据所配电机设置，出厂已设好。',
  ),
  DeviceParam(
    code: 'P00-07',
    name: '编码器选择',
    range: '0-3',
    defaultVal: '---',
    unit: '',
    change: '停机设定',
    effect: '重新上电',
    description: '1: 增量式编码器；2: 单圈绝对值编码器；3: 多圈绝对值编码器。',
  ),
  DeviceParam(
    code: 'P00-08',
    name: '省线式增量编码器',
    range: '0-1',
    defaultVal: '---',
    unit: '',
    change: '停机设定',
    effect: '重新上电',
    description: '0: 非省线式；1: 省线式。',
  ),
  DeviceParam(
    code: 'P00-09',
    name: '绝对值编码器类型',
    range: '0-2',
    defaultVal: '---',
    unit: '',
    change: '停机设定',
    effect: '重新上电',
    description: '0: 多摩川编码器；1: 尼康编码器；2: 取消多圈溢出报警。',
  ),
  DeviceParam(
    code: 'P00-10',
    name: '增量式编码器线数',
    range: '0-65535',
    defaultVal: '---',
    unit: '',
    change: '停机设定',
    effect: '重新上电',
    description: '根据所配电机设置，出厂已设好。',
  ),
  DeviceParam(
    code: 'P00-11',
    name: '增量编码器Z脉冲电角度',
    range: '0-65535',
    defaultVal: '---',
    unit: '',
    change: '停机设定',
    effect: '重新上电',
    description: '根据所配电机设置，出厂已设好。',
  ),
  DeviceParam(
    code: 'P00-12',
    name: '转子初始角1',
    range: '0-360',
    defaultVal: '---',
    unit: '1度',
    change: '停机设定',
    effect: '重新上电',
    description: '根据所配电机设置，出厂已设好。',
  ),
  DeviceParam(
    code: 'P00-13',
    name: '转子初始角2',
    range: '0-360',
    defaultVal: '---',
    unit: '1度',
    change: '停机设定',
    effect: '重新上电',
    description: '根据所配电机设置，出厂已设好。',
  ),
  DeviceParam(
    code: 'P00-14',
    name: '转子初始角3',
    range: '0-360',
    defaultVal: '---',
    unit: '1度',
    change: '停机设定',
    effect: '重新上电',
    description: '根据所配电机设置，出厂已设好。',
  ),
  DeviceParam(
    code: 'P00-15',
    name: '转子初始角4',
    range: '0-360',
    defaultVal: '---',
    unit: '1度',
    change: '停机设定',
    effect: '重新上电',
    description: '根据所配电机设置，出厂已设好。',
  ),
  DeviceParam(
    code: 'P00-16',
    name: '转子初始角5',
    range: '0-360',
    defaultVal: '---',
    unit: '1度',
    change: '停机设定',
    effect: '重新上电',
    description: '根据所配电机设置，出厂已设好。',
  ),
  DeviceParam(
    code: 'P00-17',
    name: '转子初始角6',
    range: '0-360',
    defaultVal: '---',
    unit: '1度',
    change: '停机设定',
    effect: '重新上电',
    description: '根据所配电机设置，出厂已设好。',
  ),
  DeviceParam(
    code: 'P00-20',
    name: '上电界面显示设定',
    range: '0-100',
    defaultVal: '100',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '根据客户显示需求设定。设定100时驱动器上电时显示运行状态；其它参数设定值对应监控项目一览表序号进行设定。',
  ),
  DeviceParam(
    code: 'P00-21',
    name: 'RS232通讯波特率',
    range: '0-3',
    defaultVal: '2',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '0: 9600；1: 19200；2: 57600；3: 115200。',
  ),
  DeviceParam(
    code: 'P00-23',
    name: '从站地址',
    range: '0-255',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '根据设备需求设置。',
  ),
  DeviceParam(
    code: 'P00-24',
    name: 'Modbus通讯波特率',
    range: '0-7',
    defaultVal: '2',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '0: 2400；1: 4800；2: 9600；3: 19200；4: 38400；5: 57600；6: 115200；7: 25600。',
  ),
  DeviceParam(
    code: 'P00-25',
    name: '校验方式',
    range: '0-3',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '0: 无校验2位停止位；1: 偶校验1位停止位；2: 奇校验1位停止位；3: 无校验1位停止位。',
  ),
  DeviceParam(
    code: 'P00-26',
    name: 'Modbus通讯应答延时',
    range: '0-100',
    defaultVal: '0',
    unit: '1ms',
    change: '运行设定',
    effect: '重新上电',
    description: '参数设定为0时按标准通讯进行应答，当参数设定有值时Modbus通讯应答时间按照设定时间进行应答。',
  ),
  DeviceParam(
    code: 'P00-28',
    name: '转矩控制Modbus通讯兼容设定',
    range: '0-2',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '0: 预留；1: 默认方式；2: 兼容台达地址。',
  ),
  DeviceParam(
    code: 'P00-29',
    name: 'Modbus绝对式编码器反馈格式',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '0: 84D为圈数值84E为单圈数值；1: 84D为单圈数值84E为圈数值。',
  ),
  DeviceParam(
    code: 'P00-30',
    name: '制动电阻设置',
    range: '0-2',
    defaultVal: '---',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '0: 使用内置电阻；1: 使用外置电阻；2: 不使用制动电阻。',
  ),
  DeviceParam(
    code: 'P00-31',
    name: '外接制动电阻功率',
    range: '0-65535',
    defaultVal: '---',
    unit: '10W',
    change: '运行设定',
    effect: '立即生效',
    description: '根据所外接的制动电阻正确设置，如设定值为4则电阻功率为40W。',
  ),
  DeviceParam(
    code: 'P00-32',
    name: '外接制动电阻阻值',
    range: '0-1000',
    defaultVal: '---',
    unit: '1欧姆',
    change: '运行设定',
    effect: '重新上电',
    description: '根据所外接的制动电阻正确设置。',
  ),
  DeviceParam(
    code: 'P00-33',
    name: '再生开路短路检测使能',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '0: 关闭再生开路短路检测；1: 开启再生开路短路检测使能。',
  ),
  DeviceParam(
    code: 'P00-40',
    name: '过温保护设置',
    range: '0-1',
    defaultVal: '1',
    unit: '',
    change: '停机设定',
    effect: '重新上电',
    description: '0: 关闭过温保护功能；1: 开启过温保护功能。',
  ),
  DeviceParam(
    code: 'P00-41',
    name: '控制电源掉电保护设置',
    range: '0-1',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '0: 关闭控制电源掉电保护功能；1: 开启控制电源掉电保护功能。',
  ),
  DeviceParam(
    code: 'P00-46',
    name: '速度不一致报警检测时间设定',
    range: '0-65535',
    defaultVal: '0',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 关闭速度不一致报警检测保护功能；1~65535: 设定速度不一致报警检测时间，当速度误差达到P04-12设定时间达到该设定时间，驱动器报警AL.423。',
  ),
  DeviceParam(
    code: 'P01-01',
    name: '控制模式设定',
    range: '0-6',
    defaultVal: '0',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '0: 位置控制模式；1: 速度控制模式；2: 转矩控制模式；3: 速度转矩控制模式；4: 位置速度控制模式；5: 位置转矩控制模式；6: 伺服电批功能。',
  ),
  DeviceParam(
    code: 'P01-02',
    name: '实时自动调整模式',
    range: '0-3',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 手动调整刚性；1: 标准模式自动调整刚性；2: 定位模式自动调整刚性；3: 自动调整刚性2。',
  ),
  DeviceParam(
    code: 'P01-03',
    name: '实时自动调整刚性设定',
    range: '0-31',
    defaultVal: '13',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '内置32种增益类参数，当P01-02设置成1、2、3时候起作用。可根据实际情况直接调用，设定值越大刚性越强。',
  ),
  DeviceParam(
    code: 'P01-04',
    name: '转动惯量比',
    range: '0-100.00',
    defaultVal: '3',
    unit: '1倍',
    change: '运行设定',
    effect: '立即生效',
    description: '设定相应电机的负载惯量比。P01-04=负载惯量/电机转动惯量。此惯量比可使用AF-J-L自动惯量识别后的值。',
  ),
  DeviceParam(
    code: 'P01-10',
    name: '超程后控制方式',
    range: '0-1',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 超程后电机处于自由状态只接收反方向信号运行；1: 超程后电机处于锁定状态只接收反方向信号运行。',
  ),
  DeviceParam(
    code: 'P01-20',
    name: '动态制动器延时',
    range: '0-250',
    defaultVal: '50',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '满足制动条件时动态制动器动作延时时间。',
  ),
  DeviceParam(
    code: 'P01-21',
    name: '主电源关断时禁止动态制动器',
    range: '0-1',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 使用动态制动；1: 关闭动态制动。',
  ),
  DeviceParam(
    code: 'P01-22',
    name: '伺服OFF时禁止动态制动器',
    range: '0-1',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 使用动态制动；1: 关闭动态制动。',
  ),
  DeviceParam(
    code: 'P01-23',
    name: '报警时禁止动态制动器',
    range: '0-1',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 使用动态制动；1: 关闭动态制动。',
  ),
  DeviceParam(
    code: 'P01-24',
    name: '超程时禁止动态制动器',
    range: '0-1',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 使用动态制动；1: 关闭动态制动。',
  ),
  DeviceParam(
    code: 'P01-30',
    name: '抱闸指令-伺服OFF延时时间（抱闸打开延时）',
    range: '0-255',
    defaultVal: '100',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '开使能时: 执行使能指令后经过P01-30的时间后驱动器才会接收位置指令。关使能时: 电机处于静止状态时执行关使能指令后抱闸关闭后到电机变为非通电状态的时间。',
  ),
  DeviceParam(
    code: 'P01-31',
    name: '抱闸指令输出的速度限制值',
    range: '0-3000',
    defaultVal: '100',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '电机处于旋转状态时抱闸输出有效时的电机速度门限。低于此门限时抱闸输出指令有效否则将等待P01-32时间后抱闸输出指令有效。',
  ),
  DeviceParam(
    code: 'P01-32',
    name: '伺服OFF抱闸指令等待时间',
    range: '0-255',
    defaultVal: '100',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '电机处于旋转状态时抱闸输出的最长等待时间。',
  ),
  DeviceParam(
    code: 'P01-35',
    name: 'Z信号宽度设定',
    range: '0-10000',
    defaultVal: '0',
    unit: '0.01ms',
    change: '运行设定',
    effect: '立即生效',
    description: '设0时为默认宽度；当有数值时Z信号宽度以设定时间为单位。',
  ),
  DeviceParam(
    code: 'P01-40',
    name: '失控检测使能',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '防止电机失控异常旋转。0: 关使能；1: 开使能。',
  ),
  DeviceParam(
    code: 'P02-00',
    name: '位置控制增益1',
    range: '0-3000.0',
    defaultVal: '48.0',
    unit: '1/S',
    change: '运行设定',
    effect: '立即生效',
    description: '位置环调节器的比例增益，参数值越大增益比例越高刚度越大位置跟踪误差越小响应加快。但参数过大容易引起振动和超调。此参数针对稳态响应。',
  ),
  DeviceParam(
    code: 'P02-01',
    name: '位置控制增益2',
    range: '0-3000.0',
    defaultVal: '57.0',
    unit: '1/S',
    change: '运行设定',
    effect: '立即生效',
    description: '位置环调节器的比例增益，参数值越大增益比例越高刚度越大位置跟踪误差越小响应加快。但参数过大容易引起振动和超调。此参数针对动态响应。',
  ),
  DeviceParam(
    code: 'P02-03',
    name: '速度前馈增益',
    range: '0-100.0',
    defaultVal: '30.0',
    unit: '1.0%',
    change: '运行设定',
    effect: '立即生效',
    description: '速度环的前馈增益，参数值越大系统位置跟踪误差越小响应加快。但前馈增益过大会使系统的位置环不稳定容易产生超调及震荡。',
  ),
  DeviceParam(
    code: 'P02-04',
    name: '速度前馈平滑常数',
    range: '0-64.00',
    defaultVal: '0.5',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '用于设置速度环前馈滤波时间常数。值越大滤波效果增大但同时相位滞后增大。',
  ),
  DeviceParam(
    code: 'P02-10',
    name: '速度比例增益1',
    range: '1.0-2000.0',
    defaultVal: '27.0',
    unit: '1Hz',
    change: '运行设定',
    effect: '立即生效',
    description: '速度比例增益越大伺服刚度越大速度响应越快但过大容易产生振动发出噪声。在系统不产生震荡的条件下尽量增大此参数值。此参数针对静态响应。',
  ),
  DeviceParam(
    code: 'P02-11',
    name: '速度积分常数1',
    range: '0.1-1000.0',
    defaultVal: '10.0',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '速度调节器积分时间常数，设置值越小积分速度越快刚度越大过小容易产生振动发出噪声。在系统不出现震荡的情况下尽量降低此参数值。此参数针对稳态响应。',
  ),
  DeviceParam(
    code: 'P02-12',
    name: '伪微分前馈控制系数1',
    range: '0-100.0',
    defaultVal: '100.0',
    unit: '1.0%',
    change: '运行设定',
    effect: '立即生效',
    description: '设置为100.0%时速度环采用PI控制动态响应快；设置为0时速度环积分作用明显可过滤低频干扰但动态响应慢。',
  ),
  DeviceParam(
    code: 'P02-13',
    name: '速度比例增益2',
    range: '1.0-2000.0',
    defaultVal: '27.0',
    unit: '1Hz',
    change: '运行设定',
    effect: '立即生效',
    description: '速度比例增益越大伺服刚度越大速度响应越快但过大容易产生振动发出噪声。此参数针对动态响应。',
  ),
  DeviceParam(
    code: 'P02-14',
    name: '速度积分常数2',
    range: '0.1-1000.0',
    defaultVal: '1000.0',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '速度调节器积分时间常数，设置值越小积分速度越快刚度越大过小容易产生振动发出噪声。此参数针对动态响应。',
  ),
  DeviceParam(
    code: 'P02-15',
    name: '伪微分前馈控制系数2',
    range: '0-100.0',
    defaultVal: '100.0',
    unit: '1.0%',
    change: '运行设定',
    effect: '立即生效',
    description: '设置为100.0%时速度环采用PI控制动态响应快；设置为0时速度环积分作用明显可过滤低频干扰但动态响应慢。',
  ),
  DeviceParam(
    code: 'P02-16',
    name: '速度积分误差限幅值',
    range: '0-32767',
    defaultVal: '25000',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '速度积分误差限幅值。',
  ),
  DeviceParam(
    code: 'P02-19',
    name: '转矩前馈增益',
    range: '0-30000',
    defaultVal: '0',
    unit: '1.0%',
    change: '运行设定',
    effect: '立即生效',
    description: '设定电流环前馈加权值。该参数将速度指令的微分做加权处理后加入电流环。',
  ),
  DeviceParam(
    code: 'P02-20',
    name: '转矩前馈平滑常数',
    range: '0-64.00',
    defaultVal: '0.8',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '用于设置转矩前馈滤波时间常数。',
  ),
  DeviceParam(
    code: 'P02-30',
    name: '增益切换模式',
    range: '0-10',
    defaultVal: '7',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '设置第一第二增益切换的条件。0: 固定为第一增益；1: 固定为第二增益；2: DI输入切换；3-10: 多种自动切换模式。',
  ),
  DeviceParam(
    code: 'P02-31',
    name: '增益切换等级',
    range: '0-20000',
    defaultVal: '800',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '增益切换时的判断门限值。',
  ),
  DeviceParam(
    code: 'P02-32',
    name: '增益切换迟滞',
    range: '0-20000',
    defaultVal: '100',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '增益切换时的滞回等级。',
  ),
  DeviceParam(
    code: 'P02-33',
    name: '增益切换延时',
    range: '0-1000.0',
    defaultVal: '10.0',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '从第2增益切换到第1增益时从触发条件满足到实际切换的时间。',
  ),
  DeviceParam(
    code: 'P02-34',
    name: '位置增益切换时间',
    range: '0-1000.0',
    defaultVal: '10.0',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '位置控制增益1平滑切换到位置控制增益2的时间。',
  ),
  DeviceParam(
    code: 'P02-40',
    name: '模式开关选择',
    range: '0-4',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '设定速度环PI控制和P控制的条件。',
  ),
  DeviceParam(
    code: 'P02-41',
    name: '模式开关等级',
    range: '0-20000',
    defaultVal: '10000',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '设定切换的门限值。',
  ),
  DeviceParam(
    code: 'P02-50',
    name: '转矩指令加算值',
    range: '-100.0-100.0',
    defaultVal: '0',
    unit: '1.0%',
    change: '运行设定',
    effect: '立即生效',
    description: '位置控制模式时有效。此值叠加到转矩给定值中用于垂直轴静态力矩补偿。',
  ),
  DeviceParam(
    code: 'P02-51',
    name: '正向转矩补偿',
    range: '0-100.0',
    defaultVal: '0',
    unit: '1.0%',
    change: '运行设定',
    effect: '立即生效',
    description: '位置控制模式时有效。用于补偿正向静摩擦力。',
  ),
  DeviceParam(
    code: 'P02-52',
    name: '反向转矩补偿',
    range: '-100.0-0',
    defaultVal: '0',
    unit: '1.0%',
    change: '运行设定',
    effect: '立即生效',
    description: '位置控制模式时有效。用于补偿反向静摩擦力。',
  ),
  DeviceParam(
    code: 'P02-59',
    name: '增益匹配模式',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 兼容V4.X、V5.X及老版本增益；1: 新电流环版本增益。',
  ),
  DeviceParam(
    code: 'P03-00',
    name: '位置命令来源',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '0: 脉冲指令；1: 数字给定通讯控制时使用。',
  ),
  DeviceParam(
    code: 'P03-01',
    name: '指令脉冲模式',
    range: '0-3',
    defaultVal: '1',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '0: 正交脉冲指令；1: 方向+脉冲指令；2或3: 双脉冲指令（CW+CCW）。',
  ),
  DeviceParam(
    code: 'P03-02',
    name: '指令脉冲输入端子',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '0: 低速脉冲端口；1: 高速脉冲端口。',
  ),
  DeviceParam(
    code: 'P03-03',
    name: '指令脉冲取反',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 正常；1: 方向反向。',
  ),
  DeviceParam(
    code: 'P03-04',
    name: '位置脉冲滤波',
    range: '0-3',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 0.1us；1: 1.6us；2: 3.2us；3: 6.4us。',
  ),
  DeviceParam(
    code: 'P03-05',
    name: '定位完成判断条件',
    range: '0-2',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 位置偏差小于P03-06设定值时输出；1: 位置给定完成且位置偏差小于P03-06设定值时输出；2: 位置给定完成（滤波后）且位置偏差小于P03-06设定值时输出。',
  ),
  DeviceParam(
    code: 'P03-06',
    name: '定位完成范围',
    range: '0-65535',
    defaultVal: '100',
    unit: '编码器单位',
    change: '运行设定',
    effect: '立即生效',
    description: '用于设置定位完成输出的门限值。',
  ),
  DeviceParam(
    code: 'P03-07',
    name: '位置反馈格式',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '0: 增量格式；1: 多圈绝对值格式。',
  ),
  DeviceParam(
    code: 'P03-09',
    name: '电机旋转一圈指令脉冲数',
    range: '0-65535',
    defaultVal: '10000',
    unit: 'Pulse',
    change: '运行设定',
    effect: '重新上电',
    description: '绝对式编码器电机有效。用于设定电机旋转一圈指令脉冲数。本参数设0时P03-10、P03-11参数有效。',
  ),
  DeviceParam(
    code: 'P03-10',
    name: '电子齿轮1之分子',
    range: '1-65535',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '用于设定电子齿轮比分子。详见电子齿轮比计算方式。',
  ),
  DeviceParam(
    code: 'P03-11',
    name: '电子齿轮1之分母',
    range: '1-65535',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '用于设定电子齿轮比分母。',
  ),
  DeviceParam(
    code: 'P03-12',
    name: '电子齿轮1之分子高16位',
    range: '0-32767',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '使用该参数可以放大电子齿轮比: 分子值=P03-12*10000+P03-10。',
  ),
  DeviceParam(
    code: 'P03-13',
    name: '电子齿轮2之分子',
    range: '1-65535',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '见P03-10。',
  ),
  DeviceParam(
    code: 'P03-14',
    name: '电子齿轮2之分母',
    range: '1-65535',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '见P03-11。',
  ),
  DeviceParam(
    code: 'P03-15',
    name: '位置偏差过大设置',
    range: '0-65535',
    defaultVal: '30000',
    unit: '指令单位*10',
    change: '运行设定',
    effect: '立即生效',
    description: '设置允许偏差的脉冲数，超过设定值会报警。例子: 设定值20则当跟随偏差超过20*10时驱动器即报警AL.501。',
  ),
  DeviceParam(
    code: 'P03-16',
    name: '位置指令平滑滤波时间常数',
    range: '0-1000.0',
    defaultVal: '0',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '设置位置指令平滑滤波器的时间常数。',
  ),
  DeviceParam(
    code: 'P03-20',
    name: '位置环反馈源',
    range: '0-3',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 编码器；1: 光栅尺。',
  ),
  DeviceParam(
    code: 'P03-22',
    name: '增量式编码器输出脉冲分频比分子',
    range: '1-65535',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '使用增量式编码器时设定CN1端口输出脉冲的数量。',
  ),
  DeviceParam(
    code: 'P03-23',
    name: '增量式编码器输出脉冲分频比分母',
    range: '1-65535',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '使用增量式编码器时设定CN1端口输出脉冲的分母。',
  ),
  DeviceParam(
    code: 'P03-25',
    name: '绝对值电机旋转一圈输出脉冲数',
    range: '0-60000',
    defaultVal: '2500',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '设定绝对值电机旋转一圈A、B频脉冲各自输出的数量。',
  ),
  DeviceParam(
    code: 'P03-30',
    name: '线性编码器反相',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '设定光栅尺输入A、B相序是否取反。0: 不取反；1: 取反。',
  ),
  DeviceParam(
    code: 'P03-31',
    name: '线性编码器Z脉冲的极性',
    range: '0-1',
    defaultVal: '1',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '设定光栅尺输入Z信号有效电平。0: 低电平；1: 高电平。',
  ),
  DeviceParam(
    code: 'P03-40',
    name: '输出脉冲来源',
    range: '0-3',
    defaultVal: '1',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '0: 脉冲输出报警不输出；1: 马达输出；2: 脉冲输出；3: 光栅尺。',
  ),
  DeviceParam(
    code: 'P03-41',
    name: 'AB信号输出反相',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '0: 不取反；1: 取反。',
  ),
  DeviceParam(
    code: 'P03-42',
    name: '输出Z脉冲极性',
    range: '0-1',
    defaultVal: '1',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '设定CN1端子分频输出信号Z信号有效电平。0: 低电平；1: 高电平。',
  ),
  DeviceParam(
    code: 'P03-43',
    name: '脉冲信号边沿选择',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 上升沿；1: 下降沿。',
  ),
  DeviceParam(
    code: 'P03-45',
    name: '数字位置指令缓存方式',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '0: 不缓存（立即执行）；1: 缓存（上次数据执行完后再执行新数据）。',
  ),
  DeviceParam(
    code: 'P03-46',
    name: '数字位置指令运行时马达最高转速',
    range: '0-6000',
    defaultVal: '1000',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '设定数字位置指令运行时马达最高转速。',
  ),
  DeviceParam(
    code: 'P03-50',
    name: '龙门功能使能',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '0: 关闭；1: 开启。',
  ),
  DeviceParam(
    code: 'P03-51',
    name: '龙门功能输入信号取反',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '',
  ),
  DeviceParam(
    code: 'P03-52',
    name: '龙门功能电机旋转一圈反馈脉冲数',
    range: '0-65535',
    defaultVal: '10000',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '',
  ),
  DeviceParam(
    code: 'P03-53',
    name: '龙门功能位置偏差过大设置',
    range: '0-65535',
    defaultVal: '10000',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '',
  ),
  DeviceParam(
    code: 'P03-55',
    name: '龙门同动位置比例增益',
    range: '0-200',
    defaultVal: '10',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '',
  ),
  DeviceParam(
    code: 'P03-60',
    name: '原点回归使能控制',
    range: '0-6',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '',
  ),
  DeviceParam(
    code: 'P03-61',
    name: '原点回归模式',
    range: '0-9',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '',
  ),
  DeviceParam(
    code: 'P03-65',
    name: '搜索原点开关时速度_高速',
    range: '0-1000',
    defaultVal: '100',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '',
  ),
  DeviceParam(
    code: 'P03-66',
    name: '搜索原点开关时速度_低速',
    range: '0-200',
    defaultVal: '10',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '',
  ),
  DeviceParam(
    code: 'P03-67',
    name: '搜索原点开关加减速时间',
    range: '0-5000',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '',
  ),
  DeviceParam(
    code: 'P03-68',
    name: '搜索原点最长时间限定',
    range: '0-65550',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '',
  ),
  DeviceParam(
    code: 'P04-00',
    name: '转速指令源',
    range: '0-3',
    defaultVal: '0',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '0: 外部模拟指令；1: 数字指令（参数设定）；2: 数字指令（通讯）；3: 内部多组指令。',
  ),
  DeviceParam(
    code: 'P04-01',
    name: '速度指令模拟量取反',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '0: 正常；1: 极性取反。',
  ),
  DeviceParam(
    code: 'P04-02',
    name: '数字速度给定值',
    range: '-6000-6000',
    defaultVal: '0',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '当P04-00设置为1时P04-02为转速设定值。',
  ),
  DeviceParam(
    code: 'P04-03',
    name: '零速度位置钳位功能',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 无位置钳位功能；1: 有位置钳位功能。',
  ),
  DeviceParam(
    code: 'P04-04',
    name: '零速度位置钳位速度限幅',
    range: '0-6000',
    defaultVal: '30',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '设定触发零速度位置钳位功能的速度指令门限值。',
  ),
  DeviceParam(
    code: 'P04-05',
    name: '超速报警值',
    range: '0-6500',
    defaultVal: '6400',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '设定允许最高转速值，超过设定值会AL.420超速报警。',
  ),
  DeviceParam(
    code: 'P04-06',
    name: '正向转速限制',
    range: '0-6000',
    defaultVal: '5000',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '限制电机正向转速值。',
  ),
  DeviceParam(
    code: 'P04-07',
    name: '反向转速限制',
    range: '-6000-0',
    defaultVal: '-5000',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '限制电机反向转速值。',
  ),
  DeviceParam(
    code: 'P04-10',
    name: '零速检出值',
    range: '0-200.0',
    defaultVal: '2',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '设定零速度检出门限值，电机转速低于该门限可通过输出端口输出电机零速输出信号。',
  ),
  DeviceParam(
    code: 'P04-11',
    name: '旋转检出值',
    range: '0-200.0',
    defaultVal: '30',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '设定电机旋转检出门限，电机转速高于该值可通过LED面板显示状态。',
  ),
  DeviceParam(
    code: 'P04-12',
    name: '速度一致幅度',
    range: '0-200.0',
    defaultVal: '30',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '设定速度一致信号的门限值，当电机转速与指令转速差值在该门限值范围内可通过输出端口输出速度一致输出信号。',
  ),
  DeviceParam(
    code: 'P04-14',
    name: '加速时间',
    range: '0-10000',
    defaultVal: '0',
    unit: '1ms/1000rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '设定速度控制时的加速度。',
  ),
  DeviceParam(
    code: 'P04-15',
    name: '减速时间',
    range: '0-10000',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '设定速度控制时的减速度。',
  ),
  DeviceParam(
    code: 'P04-30',
    name: '内部设定速度1',
    range: '-6000-6000',
    defaultVal: '0',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '内部转速1设定值。',
  ),
  DeviceParam(
    code: 'P04-31',
    name: '内部设定速度2',
    range: '-6000-6000',
    defaultVal: '0',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '内部转速2设定值。',
  ),
  DeviceParam(
    code: 'P04-32',
    name: '内部设定速度3',
    range: '-6000-6000',
    defaultVal: '0',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '内部转速3设定值。',
  ),
  DeviceParam(
    code: 'P04-33',
    name: '内部设定速度4',
    range: '-6000-6000',
    defaultVal: '0',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '内部转速4设定值。',
  ),
  DeviceParam(
    code: 'P04-34',
    name: '内部设定速度5',
    range: '-6000-6000',
    defaultVal: '0',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '内部转速5设定值。',
  ),
  DeviceParam(
    code: 'P04-35',
    name: '内部设定速度6',
    range: '-6000-6000',
    defaultVal: '0',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '内部转速6设定值。',
  ),
  DeviceParam(
    code: 'P04-36',
    name: '内部设定速度7',
    range: '-6000-6000',
    defaultVal: '0',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '内部转速7设定值。',
  ),
  DeviceParam(
    code: 'P04-37',
    name: '内部设定速度8',
    range: '-6000-6000',
    defaultVal: '0',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '内部转速8设定值。',
  ),
  DeviceParam(
    code: 'P05-00',
    name: '转矩指令源',
    range: '0-3',
    defaultVal: '0',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '0: 外部模拟指令（速度限幅值由P05-02设定）；1: 数字指令（速度限幅值由P05-02设定）；2: 外部模拟指令（速度限幅值由速度模拟指令确定）；3: 数字指令（速度限幅值由速度模拟指令确定）。',
  ),
  DeviceParam(
    code: 'P05-01',
    name: '转矩指令模拟量取反',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '0: 正常；1: 方向反向。',
  ),
  DeviceParam(
    code: 'P05-02',
    name: '转矩模式速度限幅给定值',
    range: '0-5000',
    defaultVal: '1500',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '设定转矩模式时的电机最高速度值，防止空载时电机速度过高导致机械损坏。',
  ),
  DeviceParam(
    code: 'P05-03',
    name: '数字转矩给值',
    range: '0-300.0',
    defaultVal: '0',
    unit: '1.0%',
    change: '运行设定',
    effect: '立即生效',
    description: '当P05-00设置为1时P05-03为数字转矩给定初始值。',
  ),
  DeviceParam(
    code: 'P05-05',
    name: '转矩限幅设定源',
    range: '0-2',
    defaultVal: '0',
    unit: '',
    change: '停机设定',
    effect: '立即生效',
    description: '0: 内部数字量；1: 外部模拟量；2: 转矩限幅由参数P05-03限制。',
  ),
  DeviceParam(
    code: 'P05-06',
    name: '转矩限制检出输出延时',
    range: '0-10000',
    defaultVal: '0',
    unit: 'ms',
    change: '运行设定',
    effect: '立即生效',
    description: '设定DO端口输出转矩限制检出输出信号延时时间。',
  ),
  DeviceParam(
    code: 'P05-10',
    name: '内部正向转矩限幅值',
    range: '0-300.0',
    defaultVal: '200.0',
    unit: '1.0%',
    change: '运行设定',
    effect: '立即生效',
    description: '限制电机正向出力，100表示1倍转矩300表示3倍转矩。',
  ),
  DeviceParam(
    code: 'P05-11',
    name: '内部反向转矩限幅值',
    range: '-300-0',
    defaultVal: '-200.0',
    unit: '1.0%',
    change: '运行设定',
    effect: '立即生效',
    description: '限制电机反向出力。',
  ),
  DeviceParam(
    code: 'P05-12',
    name: '外部正向转矩限幅值',
    range: '0-300.0',
    defaultVal: '100.0',
    unit: '1.0%',
    change: '运行设定',
    effect: '立即生效',
    description: '使用DI端口切换外部转矩限幅时有效。',
  ),
  DeviceParam(
    code: 'P05-13',
    name: '外部反向转矩限幅值',
    range: '-300-0',
    defaultVal: '-100.0',
    unit: '1.0%',
    change: '运行设定',
    effect: '立即生效',
    description: '使用DI端口切换外部转矩限幅时有效。',
  ),
  DeviceParam(
    code: 'P06-00',
    name: 'DI1输入端口有效电平',
    range: '0-4',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '0: 低电平有效（光耦导通）；1: 高电平有效（光耦截止）；2: 上升沿有效；3: 下降沿有效；4: 上升下降沿均有效。',
  ),
  DeviceParam(
    code: 'P06-01',
    name: 'DI1输入端口功能选择',
    range: '0-24',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '出厂设置: 1 伺服ON。详见功能选择说明。',
  ),
  DeviceParam(
    code: 'P06-02',
    name: 'DI2输入端口有效电平',
    range: '0-4',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '见P06-00。',
  ),
  DeviceParam(
    code: 'P06-03',
    name: 'DI2输入端口功能选择',
    range: '0-24',
    defaultVal: '2',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '出厂设置: 2 报警清除。',
  ),
  DeviceParam(
    code: 'P06-04',
    name: 'DI3输入端口有效电平',
    range: '0-4',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '见P06-00。',
  ),
  DeviceParam(
    code: 'P06-05',
    name: 'DI3输入端口功能选择',
    range: '0-24',
    defaultVal: '3',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '出厂设置: 3 正向超程信号输入。',
  ),
  DeviceParam(
    code: 'P06-06',
    name: 'DI4输入端口有效电平',
    range: '0-4',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '见P06-00。',
  ),
  DeviceParam(
    code: 'P06-07',
    name: 'DI4输入端口功能选择',
    range: '0-24',
    defaultVal: '4',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '出厂设置: 4 反向超程信号输入。',
  ),
  DeviceParam(
    code: 'P06-08',
    name: 'DI5输入端口有效电平',
    range: '0-4',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '见P06-00。',
  ),
  DeviceParam(
    code: 'P06-09',
    name: 'DI5输入端口功能选择',
    range: '0-24',
    defaultVal: '7',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '出厂设置: 7 正转侧外部转矩限制。',
  ),
  DeviceParam(
    code: 'P06-10',
    name: 'DI6输入端口有效电平',
    range: '0-4',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '见P06-00。',
  ),
  DeviceParam(
    code: 'P06-11',
    name: 'DI6输入端口功能选择',
    range: '0-24',
    defaultVal: '8',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '出厂设置: 8 反转侧外部转矩限制。',
  ),
  DeviceParam(
    code: 'P06-12',
    name: 'DI7输入端口有效电平',
    range: '0-4',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '见P06-00。',
  ),
  DeviceParam(
    code: 'P06-13',
    name: 'DI7输入端口功能选择',
    range: '0-24',
    defaultVal: '5',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '出厂设置: 5 控制模式切换。',
  ),
  DeviceParam(
    code: 'P06-16',
    name: 'DI8输入端口有效电平',
    range: '0-4',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '见P06-00。',
  ),
  DeviceParam(
    code: 'P06-17',
    name: 'DI8输入端口功能选择',
    range: '0-24',
    defaultVal: '16',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '出厂设置: 16 位置命令清零输入。',
  ),
  DeviceParam(
    code: 'P06-20',
    name: 'DO1输出端口有效电平',
    range: '0-1',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '0: 状态有效时光耦截止；1: 状态有效时光耦导通。',
  ),
  DeviceParam(
    code: 'P06-21',
    name: 'DO1输出端口功能选择',
    range: '0-13',
    defaultVal: '3',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '出厂设置: 3 伺服准备好输出。详见功能选择说明。',
  ),
  DeviceParam(
    code: 'P06-22',
    name: 'DO2输出端口有效电平',
    range: '0-1',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '见P06-20。',
  ),
  DeviceParam(
    code: 'P06-23',
    name: 'DO2输出端口功能选择',
    range: '0-13',
    defaultVal: '2',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '出厂设置: 2 抱闸打开输出。',
  ),
  DeviceParam(
    code: 'P06-24',
    name: 'DO3输出端口有效电平',
    range: '0-1',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '见P06-20。',
  ),
  DeviceParam(
    code: 'P06-25',
    name: 'DO3输出端口功能选择',
    range: '0-13',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '出厂设置: 1 报警输出。',
  ),
  DeviceParam(
    code: 'P06-26',
    name: 'DO4输出端口有效电平',
    range: '0-1',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '见P06-20。',
  ),
  DeviceParam(
    code: 'P06-27',
    name: 'DO4输出端口功能选择',
    range: '0-13',
    defaultVal: '4',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '出厂设置: 4 定位完成输出。',
  ),
  DeviceParam(
    code: 'P06-28',
    name: 'DO5输出端口有效电平',
    range: '0-1',
    defaultVal: '1',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '见P06-20。',
  ),
  DeviceParam(
    code: 'P06-29',
    name: 'DO5输出端口功能选择',
    range: '0-13',
    defaultVal: '8',
    unit: '',
    change: '运行设定',
    effect: '重新上电',
    description: '出厂设置: 8 转矩限制检出输出。',
  ),
  DeviceParam(
    code: 'P06-40',
    name: '速度模拟指令输入增益',
    range: '10-2000',
    defaultVal: '300',
    unit: '1rpm/V',
    change: '运行设定',
    effect: '立即生效',
    description: '设定CN1输入的模拟指令与速度控制指令之间的系数。例: 500代表每V对应500转每分钟。',
  ),
  DeviceParam(
    code: 'P06-41',
    name: '速度模拟命令滤波常数',
    range: '0-64.00',
    defaultVal: '0.8',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '设定CN1输入的模拟指令滤波时间系数。',
  ),
  DeviceParam(
    code: 'P06-42',
    name: '速度模拟指令偏移量',
    range: '-10.000-10.000',
    defaultVal: '0',
    unit: '1V',
    change: '运行设定',
    effect: '立即生效',
    description: '设定CN1输入的模拟指令零点偏移量。',
  ),
  DeviceParam(
    code: 'P06-43',
    name: '转矩模拟指令增益',
    range: '0.0-100.0',
    defaultVal: '10',
    unit: '%',
    change: '运行设定',
    effect: '立即生效',
    description: '设定CN1输入的模拟指令与速度控制指令之间的系数。',
  ),
  DeviceParam(
    code: 'P06-44',
    name: '转矩模拟指令滤波常数',
    range: '0-64.00',
    defaultVal: '0.8',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '设定CN1输入的模拟指令滤波时间系数。',
  ),
  DeviceParam(
    code: 'P06-45',
    name: '转矩模拟指令偏移量',
    range: '-10.000-10.000',
    defaultVal: '0',
    unit: '1V',
    change: '运行设定',
    effect: '立即生效',
    description: '设定CN1输入的模拟指令零点偏移量。',
  ),
  DeviceParam(
    code: 'P06-46',
    name: '速度模拟指令死区',
    range: '0-10.000',
    defaultVal: '0',
    unit: '1V',
    change: '运行设定',
    effect: '立即生效',
    description: '设定速度模拟指令的死区电压值，模拟量给定在该正负值范围内时系统默认给定为零。',
  ),
  DeviceParam(
    code: 'P06-47',
    name: '转矩模拟指令死区',
    range: '0-10.000',
    defaultVal: '0',
    unit: '1V',
    change: '运行设定',
    effect: '立即生效',
    description: '设定转矩模拟指令的死区电压值，模拟量给定在该正负值范围内时系统默认给定为零。',
  ),
  DeviceParam(
    code: 'P08-01',
    name: '负载转动惯量辨识模式',
    range: '0-1',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 有效；1: 无效。',
  ),
  DeviceParam(
    code: 'P08-02',
    name: '惯量辨识最大速度',
    range: '100-2000',
    defaultVal: '800',
    unit: '1rpm',
    change: '运行设定',
    effect: '立即生效',
    description: '离线惯量辨识时电机的最高转速。',
  ),
  DeviceParam(
    code: 'P08-03',
    name: '惯量辨识加减速时间',
    range: '20-800',
    defaultVal: '100',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '离线惯量辨识时电机的加减速时间。',
  ),
  DeviceParam(
    code: 'P08-04',
    name: '单次惯量辨识完成后等待时间',
    range: '50-10000',
    defaultVal: '1000',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '离线惯量辨识时单次惯量辨识完成后等待时间。',
  ),
  DeviceParam(
    code: 'P08-05',
    name: '完成单次惯量需电机转动圈数',
    range: '',
    defaultVal: '1.33',
    unit: '圈',
    change: '运行设定',
    effect: '只读',
    description: '根据P08-02、P08-03、P08-04设定条件自动生成的转动圈数值。',
  ),
  DeviceParam(
    code: 'P08-11',
    name: '自适应陷波器模式选择',
    range: '0-4',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 第三第四陷波器参数不再自动更新；1: 1个自适应陷波器有效；2: 2个自适应陷波器有效；3: 仅检测共振频率；4: 清除第三四陷波器参数。',
  ),
  DeviceParam(
    code: 'P08-13',
    name: '自适应陷波器振动检出门限',
    range: '1-7',
    defaultVal: '3',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '设定自适应陷波器振动检出灵敏度，参数值越小检出灵敏度越灵敏。',
  ),
  DeviceParam(
    code: 'P08-17',
    name: '速度观测器',
    range: '0-2',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '0: 关闭速度观测器；1: 打开速度观测器；2: 速度转矩观测器。',
  ),
  DeviceParam(
    code: 'P08-19',
    name: '反馈速度低通滤波常数',
    range: '0-25.00',
    defaultVal: '0.8',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '反馈速度低通滤波时间常数，当电机运行中出现啸叫时可适当把该值设大。',
  ),
  DeviceParam(
    code: 'P08-20',
    name: '转矩命令滤波常数1',
    range: '0-25.00',
    defaultVal: '0.8',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '转矩指令滤波时间常数1，当电机运行中出现啸叫时可适当把该值设大。',
  ),
  DeviceParam(
    code: 'P08-21',
    name: '转矩命令滤波常数2',
    range: '0-25.00',
    defaultVal: '0.8',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '转矩指令滤波时间常数2，当电机运行中出现啸叫时可适当把该值设大。',
  ),
  DeviceParam(
    code: 'P08-25',
    name: '扰动转矩补偿增益',
    range: '0-100.0',
    defaultVal: '0',
    unit: '%',
    change: '运行设定',
    effect: '立即生效',
    description: '扰动转矩观测值得增益系数。该值越大则抗扰动力矩能力越强但动作噪声亦可能加大。',
  ),
  DeviceParam(
    code: 'P08-26',
    name: '扰动转矩滤波时间常数',
    range: '0-25.00',
    defaultVal: '0.8',
    unit: '1ms',
    change: '运行设定',
    effect: '立即生效',
    description: '数值越大滤波效果越强可抑制动作噪声。但过大会导致相位延迟反而影响扰动力矩抑制效果。',
  ),
  DeviceParam(
    code: 'P08-30',
    name: '陷波滤波器1频率',
    range: '300-5000',
    defaultVal: '5000',
    unit: 'HZ',
    change: '运行设定',
    effect: '立即生效',
    description: '陷波器1的中心频率。设定为5000时陷波器无效。',
  ),
  DeviceParam(
    code: 'P08-31',
    name: '陷波滤波器1宽度',
    range: '0-20',
    defaultVal: '2',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '陷波器1的陷波宽度等级。',
  ),
  DeviceParam(
    code: 'P08-32',
    name: '陷波滤波器1深度',
    range: '0-99',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '陷波器1的陷波深度等级。此参数越大陷波深度越小效果越弱。',
  ),
  DeviceParam(
    code: 'P08-33',
    name: '陷波滤波器2频率',
    range: '300-5000',
    defaultVal: '5000',
    unit: 'HZ',
    change: '运行设定',
    effect: '立即生效',
    description: '同P08-30。',
  ),
  DeviceParam(
    code: 'P08-34',
    name: '陷波滤波器2宽度',
    range: '0-20',
    defaultVal: '2',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '同P08-31。',
  ),
  DeviceParam(
    code: 'P08-35',
    name: '陷波滤波器2深度',
    range: '0-99',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '同P08-32。',
  ),
  DeviceParam(
    code: 'P08-36',
    name: '陷波滤波器3频率',
    range: '300-5000',
    defaultVal: '5000',
    unit: 'HZ',
    change: '运行设定',
    effect: '立即生效',
    description: '同P08-30。',
  ),
  DeviceParam(
    code: 'P08-37',
    name: '陷波滤波器3宽度',
    range: '0-20',
    defaultVal: '2',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '同P08-31。',
  ),
  DeviceParam(
    code: 'P08-38',
    name: '陷波滤波器3深度',
    range: '0-99',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '同P08-32。',
  ),
  DeviceParam(
    code: 'P08-39',
    name: '陷波滤波器4频率',
    range: '300-5000',
    defaultVal: '5000',
    unit: 'HZ',
    change: '运行设定',
    effect: '立即生效',
    description: '同P08-30。',
  ),
  DeviceParam(
    code: 'P08-40',
    name: '陷波滤波器4宽度',
    range: '0-20',
    defaultVal: '2',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '同P08-31。',
  ),
  DeviceParam(
    code: 'P08-41',
    name: '陷波滤波器4深度',
    range: '0-99',
    defaultVal: '0',
    unit: '',
    change: '运行设定',
    effect: '立即生效',
    description: '同P08-32。',
  ),
];